services:
  db:
    restart: always
    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    restart: always
    logging: *default_logging

  backend:
    restart: always
    logging: *default_logging
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 3g

  admin-spa:
    restart: always
    logging: *default_logging

  mini-app:
    restart: always
    logging: *default_logging

  nginx:
    restart: always
    logging: *default_logging
