const fs = require("fs");
const path = require("path");

const TENANT = process.env.TENANT || "gdufs";
const configPath = path.resolve(__dirname, "tenants", `${TENANT}.json`);

if (!fs.existsSync(configPath)) {
  console.error(`Tenant config not found: ${configPath}`);
  process.exit(1);
}

const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
const outputPath = path.resolve(__dirname, "src", "tenant.config.ts");

const content = `// Auto-generated by build.config.js — DO NOT EDIT
// Tenant: ${config.tenantSlug}
const tenantConfig = ${JSON.stringify(config, null, 2)} as const;
export default tenantConfig;
`;

fs.writeFileSync(outputPath, content);
console.log(`Generated tenant.config.ts for: ${config.tenantSlug}`);
